---
- hosts: jenkins
  gather_facts: yes

  vars_files:
    - vars/main.yml

  roles:
    - geerlingguy.firewall
    - geerlingguy.ntp
    - geerlingguy.git
    - geerlingguy.java
    - geerlingguy.jenkins
    - geerlingguy.docker
    - geerlingguy.pip
    - geerlingguy.ansible

  tasks:
    - name:  Adds jenkins user into docker group
      shell: usermod -a -G docker jenkins
