---
- hosts: jenkinsci
  gather_facts: yes

  vars_files:
    - vars/main.yml

  roles:
    - geerlingguy.firewall
    - geerlingguy.ntp
    - geerlingguy.git
    - geerlingguy.java
    - geerlingguy.jenkins
    - geerlingguy.docker
    - geerlingguy.pip
    - geerlingguy.ansible

  tasks:
    - name:  Adds jenkins user into docker group
      shell: usermod -a -G docker jenkins

    - name:  Adds jenkins user into docker group
      shell: usermod -a -G docker vagrant

    - name:  give permission to docker.sock
      shell: chmod 777 /var/run/docker.sock

- hosts: dev
  gather_facts: yes

  vars_files:
    - vars/main.yml

  roles:
    - geerlingguy.firewall
    - geerlingguy.ntp
    - geerlingguy.git
    - geerlingguy.docker

  tasks:
    - name:  Adds jenkins user into docker group
      shell: usermod -a -G docker vagrant

    - name:  give permission to docker.sock
      shell: chmod 777 /var/run/docker.sock
